# docker-compose.yaml

  version: '3'
  services: 
    httpd-server: 
      image: 'httpd'
      ports:
        - "80:80"
      volumes:
        - "/mnt/cicd/pipeline:/usr/local/tomcat/webapps"
    tomcat-server:
      image: 'tomcat:9'
      ports:
        - "8080-8085:8080"
      volumes:        
        - "/mnt/cicd/pipeline:/usr/local/tomcat/webapps"         
                                                                                      

